# Generated by Django 3.2.12 on 2022-03-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flange_number', models.IntegerField()),
                ('torque', models.IntegerField()),
                ('aks_number', models.CharField(max_length=200)),
                ('qr_code', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
