# Generated by Django 3.2.12 on 2022-03-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flange',
            name='qr_code',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
