# Generated by Django 3.2.12 on 2022-03-22 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0002_alter_flange_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flange',
            name='qr_code',
        ),
    ]
